'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmAberturaDia

    '''<summary>
    '''frmAberturaDia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmAberturaDia As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''optOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optOperacao As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpresa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstBoxEmpresas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstBoxEmpresas As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cboData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboData As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDataFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHoraFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoraFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dtgResponsaveis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtgResponsaveis As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''cboEquipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEquipe As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUsuario As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''optTipoOperacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optTipoOperacao As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnIncluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIncluir As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnExecutar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExecutar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnAguarde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAguarde As Global.System.Web.UI.WebControls.Label
End Class
