'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmColManutencaoUG

    '''<summary>
    '''frmColManutencaoUG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmColManutencaoUG As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtCod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodExterno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodExterno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboGerador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGerador As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDataInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataInicial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboHoraInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboHoraInicial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtDataFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cboHoraFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboHoraFinal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''optNivel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optNivel As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cboContinuidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboContinuidade As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboVoltaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboVoltaInicial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboVoltaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboVoltaFinal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnVoltar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVoltar As Global.System.Web.UI.WebControls.ImageButton
End Class
