'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmColOfertaSemanalDespComp

    '''<summary>
    '''frmColOfertaSemanalDespComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmColOfertaSemanalDespComp As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''DdlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlEmpresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PMOConsultaRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PMOConsultaRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''PMOEdicaoRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PMOEdicaoRadioButton As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''DataLimiteEnvioConsultaLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataLimiteEnvioConsultaLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DataLimiteEnvioEdicaoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataLimiteEnvioEdicaoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tblOfertaSemanalDespComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblOfertaSemanalDespComp As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''btnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalvar As Global.System.Web.UI.WebControls.ImageButton
End Class
