'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmEnviaDados

    '''<summary>
    '''frmEnviarDados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmEnviarDados As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cboData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboData As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cboEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEmpresa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEnviar As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkGeracao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGeracao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnvia1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnvia1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCarga As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIntercambio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIntercambio As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVazao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVazao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVazE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVazE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnviaTodos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnviaTodos As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''chkInflexibilidade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInflexibilidade As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIfxE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIfxE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnergetica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnergetica As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkZenE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkZenE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEletrica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEletrica As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkZelE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkZelE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkExporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExporta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkExpE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExpE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkImporta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImporta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkImpE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImpE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMRE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMreE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMreE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMIF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMIF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMifE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMifE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPCC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPccE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPccE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMCO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMCO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMcoE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMcoE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMOS As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMosE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMosE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMEG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMEG As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkMegE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMegE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkERP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkERP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkErpE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkErpE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDSP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDspE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDspE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCLF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCLF As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkClfE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClfE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPCO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPCO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPcoE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPcoE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRFC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRfcE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRfcE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRMP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRMP As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRmpE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRmpE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGFM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGfmE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGfmE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCFM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCFM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCfmE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCfmE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSOM As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSomE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSomE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGES As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGesE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGesE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGEC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGEC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGecE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGecE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDCA As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDcaE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDcaE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDCR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDCR As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkDcrE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDcrE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIR1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIr1E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIr1E As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIR2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIr2E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIr2E As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIR3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIR3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIr3E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIr3E As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIR4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIR4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkIr4E control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIr4E As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRRO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRRO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRROE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRROE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkRestricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRestricao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnvia2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnvia2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkManutencao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkManutencao As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tblMensa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMensa As Global.System.Web.UI.WebControls.Table
End Class
