'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmUploadRel

    '''<summary>
    '''frmUploadRel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmUploadRel As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblDataPdp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataPdp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''drpDownDataPDP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDownDataPDP As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblArquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArquivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fl_Arquivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fl_Arquivo As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''btnConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmar As Global.System.Web.UI.WebControls.ImageButton
End Class
