'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PDPProgSemanal
    
    '''<summary>
    '''PDPProgSemanal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PDPProgSemanal As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''DdlEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlEmpresa As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LblSemanaPMO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblSemanaPMO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DdlUsinaProgramacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlUsinaProgramacao As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EdtVolumeProgramacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdtVolumeProgramacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EdtPrecoProgramacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdtPrecoProgramacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DdlUsinaTempoReal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlUsinaTempoReal As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''EdtVolumeTempoReal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdtVolumeTempoReal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''EdtPrecoTempoReal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EdtPrecoTempoReal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ChkDependentes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkDependentes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BtnSalvar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSalvar As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnIncluirNovo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnIncluirNovo As Global.System.Web.UI.WebControls.ImageButton
End Class
