'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace Ons.Rpdp.Servico.WsDespachoGeracao
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WsDespachoGeracaoSoap", [Namespace]:="http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao")>  _
    Public Class WsDespachoGeracao
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Dim urlSetting As String = System.Configuration.ConfigurationSettings.AppSettings("pdpw.Ons.Rpdp.Servico.WsDespachoGeracao.WsDespachoGeracao")
            If (Not (urlSetting) Is Nothing) Then
                Me.Url = String.Concat(urlSetting, "")
            Else
                Me.Url = "http://localhost/WsDespachoGeracao/WsDespachoGeracao.asmx"
            End If
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao/ObterDespacho", RequestNamespace:="http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao", ResponseNamespace:="http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterDespacho(ByVal Usina As String, ByVal DataInicio As String, ByVal DataTermino As String, ByVal TipoDespacho As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ObterDespacho", New Object() {Usina, DataInicio, DataTermino, TipoDespacho})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginObterDespacho(ByVal Usina As String, ByVal DataInicio As String, ByVal DataTermino As String, ByVal TipoDespacho As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterDespacho", New Object() {Usina, DataInicio, DataTermino, TipoDespacho}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterDespacho(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao/ObterTipoDespacho", RequestNamespace:="http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao", ResponseNamespace:="http://tempuri.org/WsDespachoGeracao/WsDespachoGeracao", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObterTipoDespacho() As System.Data.DataSet
            Dim results() As Object = Me.Invoke("ObterTipoDespacho", New Object(-1) {})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginObterTipoDespacho(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ObterTipoDespacho", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndObterTipoDespacho(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
