// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDPW.Infrastructure.Data;

#nullable disable

namespace PDPW.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PdpwDbContext))]
    [Migration("20251219124913_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PDPW.Domain.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoCompleto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiretorioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiretorioId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processado")
                        .HasColumnType("bit");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("ArquivosDadger");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadgerValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArquivoDadgerId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Linha")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoDadgerId");

                    b.HasIndex("Chave");

                    b.ToTable("ArquivosDadgerValores");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Balanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Carga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deficit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Geracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Intercambio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Perdas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubsistemaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaId");

                    b.ToTable("Balancos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Carga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CargaMWmed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CargaVerificada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrevisaoCarga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubsistemaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaId");

                    b.ToTable("Cargas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("DadosConsolidados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAprovacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("DCAs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("DCAId")
                        .HasColumnType("int");

                    b.Property<string>("DadosRevisados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRevisao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DCAId");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DadoEnergetico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeDisponivel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoUsina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProducaoMWh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia");

                    b.ToTable("DadosEnergeticos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiretorioPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DiretorioPaiId");

                    b.ToTable("Diretorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.HasIndex("Nome");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CNPJ = "00.341.583/0001-71",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@itaipu.gov.br",
                            Endereco = "Av. Tancredo Neves, 6731 - Foz do Iguaçu, PR",
                            Nome = "Itaipu Binacional",
                            Telefone = "(45) 3520-5252"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CNPJ = "00.357.038/0001-16",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@eletronorte.gov.br",
                            Endereco = "SCN - Quadra 6 - Conjunto A - Bloco C - Brasília, DF",
                            Nome = "Eletronorte - Centrais Elétricas do Norte do Brasil",
                            Telefone = "(61) 3429-5151"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CNPJ = "23.047.150/0001-13",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ouvidoria@furnas.com.br",
                            Endereco = "Rua Real Grandeza, 219 - Rio de Janeiro, RJ",
                            Nome = "Furnas Centrais Elétricas",
                            Telefone = "(21) 2528-5600"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CNPJ = "33.541.368/0001-16",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faleconosco@chesf.gov.br",
                            Endereco = "Rua Delmiro Gouveia, 333 - Recife, PE",
                            Nome = "Chesf - Companhia Hidro Elétrica do São Francisco",
                            Telefone = "(81) 3229-2300"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CNPJ = "00.073.957/0001-46",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "comunicacao@eletrosul.gov.br",
                            Endereco = "Av. Prefeito Osmar Cunha, 183 - Florianópolis, SC",
                            Nome = "Eletrosul Centrais Elétricas",
                            Telefone = "(48) 3231-7000"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CNPJ = "60.933.603/0001-78",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ouvidoria@cesp.com.br",
                            Endereco = "Av. Nossa Senhora do Sabará, 5312 - São Paulo, SP",
                            Nome = "CESP - Companhia Energética de São Paulo",
                            Telefone = "(11) 3138-7000"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CNPJ = "42.540.211/0001-67",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eletronuclear@eletronuclear.gov.br",
                            Endereco = "Rua da Candelária, 65 - Rio de Janeiro, RJ",
                            Nome = "Eletronuclear - Eletrobrás Termonuclear",
                            Telefone = "(21) 2588-1000"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CNPJ = "76.483.817/0001-20",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "copel@copel.com",
                            Endereco = "Rua José Izidoro Biazetto, 158 - Curitiba, PR",
                            Nome = "COPEL - Companhia Paranaense de Energia",
                            Telefone = "(41) 3331-4011"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.EquipePDP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Coordenador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EquipesPDP");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.GerForaMerito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GeracaoMWmed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("GeracoesForaMerito");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.InflexibilidadeContratada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GeracaoMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("InflexibilidadesContratadas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Intercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergiaIntercambiada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsistemaDestino")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SubsistemaOrigem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaOrigem", "SubsistemaDestino");

                    b.ToTable("Intercambios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ModalidadeOpTermica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CustoOperacional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PotenciaMaxima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotenciaMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ModalidadesOpTermica");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.MotivoRestricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MotivosRestricao");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Observacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioAutor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Observacoes");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ParadaUG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoParada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Programada")
                        .HasColumnType("bit");

                    b.Property<int>("UnidadeGeradoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeGeradoraId");

                    b.ToTable("ParadasUG");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RampasUsinaTermica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RampaDescida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RampaSubida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TempoParada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TempoPartida")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("RampasUsinasTermicas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parametros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRelatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioGeracao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotivoRestricaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PotenciaRestrita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadeGeradoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoRestricaoId");

                    b.HasIndex("UnidadeGeradoraId");

                    b.ToTable("RestricoesUG");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeRestrita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotivoRestricaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoRestricaoId");

                    b.HasIndex("UsinaId");

                    b.ToTable("RestricoesUS");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.SemanaPMO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "Ano")
                        .IsUnique();

                    b.ToTable("SemanasPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.TipoUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FonteEnergia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("TiposUsina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da força da água",
                            FonteEnergia = "Hídrica",
                            Nome = "Hidrelétrica"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da queima de combustíveis",
                            FonteEnergia = "Combustíveis Fósseis / Biomassa",
                            Nome = "Térmica"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da força dos ventos",
                            FonteEnergia = "Eólica",
                            Nome = "Eólica"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da luz solar",
                            FonteEnergia = "Solar",
                            Nome = "Solar"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da fissão nuclear",
                            FonteEnergia = "Nuclear",
                            Nome = "Nuclear"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataComissionamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PotenciaMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotenciaNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsinaId");

                    b.ToTable("UnidadesGeradoras");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeInstalada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoUsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Nome");

                    b.HasIndex("TipoUsinaId");

                    b.ToTable("Usinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CapacidadeInstalada = 14000.00m,
                            Codigo = "UHE-ITAIPU",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1984, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 1,
                            Localizacao = "Foz do Iguaçu, PR - Fronteira Brasil/Paraguai",
                            Nome = "Usina Hidrelétrica de Itaipu",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CapacidadeInstalada = 11233.00m,
                            Codigo = "UHE-BELO-MONTE",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2016, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Altamira, PA - Rio Xingu",
                            Nome = "Usina Hidrelétrica Belo Monte",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CapacidadeInstalada = 8370.00m,
                            Codigo = "UHE-TUCURUI",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Tucuruí, PA - Rio Tocantins",
                            Nome = "Usina Hidrelétrica de Tucuruí",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CapacidadeInstalada = 1710.00m,
                            Codigo = "UHE-SAO-SIMAO",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1978, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 3,
                            Localizacao = "São Simão, GO - Rio Paranaíba",
                            Nome = "Usina Hidrelétrica de São Simão",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CapacidadeInstalada = 1050.40m,
                            Codigo = "UHE-SOBRADINHO",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1979, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 4,
                            Localizacao = "Sobradinho, BA - Rio São Francisco",
                            Nome = "Usina Hidrelétrica de Sobradinho",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CapacidadeInstalada = 2082.00m,
                            Codigo = "UHE-ITUMBIARA",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1980, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 3,
                            Localizacao = "Itumbiara, GO - Rio Paranaíba",
                            Nome = "Usina Hidrelétrica de Itumbiara",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CapacidadeInstalada = 338.00m,
                            Codigo = "UTE-TERMO-MARANHAO",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2013, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Miranda do Norte, MA",
                            Nome = "Usina Termelétrica do Maranhão",
                            TipoUsinaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CapacidadeInstalada = 720.00m,
                            Codigo = "UTE-TERMO-PECEM",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2012, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 4,
                            Localizacao = "São Gonçalo do Amarante, CE",
                            Nome = "Usina Termelétrica de Pecém",
                            TipoUsinaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CapacidadeInstalada = 640.00m,
                            Codigo = "UTN-ANGRA-I",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 7,
                            Localizacao = "Angra dos Reis, RJ",
                            Nome = "Usina Termonuclear Angra I",
                            TipoUsinaId = 5
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CapacidadeInstalada = 1350.00m,
                            Codigo = "UTN-ANGRA-II",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 7,
                            Localizacao = "Angra dos Reis, RJ",
                            Nome = "Usina Termonuclear Angra II",
                            TipoUsinaId = 5
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UsinaConversora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeConversao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Eficiencia")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConversao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("UsinasConversoras");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EquipePDPId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Perfil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EquipePDPId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Arquivo", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Diretorio", "Diretorio")
                        .WithMany("Arquivos")
                        .HasForeignKey("DiretorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretorio");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("ArquivosDadger")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadgerValor", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.ArquivoDadger", "ArquivoDadger")
                        .WithMany("Valores")
                        .HasForeignKey("ArquivoDadgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArquivoDadger");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("DCAs")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCR", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.DCA", "DCA")
                        .WithMany("DCRs")
                        .HasForeignKey("DCAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("DCRs")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DCA");

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Diretorio", "DiretorioPai")
                        .WithMany("Subdiretorios")
                        .HasForeignKey("DiretorioPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiretorioPai");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.GerForaMerito", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("GeracoesForaMerito")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.InflexibilidadeContratada", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("InflexibilidadesContratadas")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ParadaUG", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.UnidadeGeradora", "UnidadeGeradora")
                        .WithMany("Paradas")
                        .HasForeignKey("UnidadeGeradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeGeradora");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RampasUsinaTermica", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("RampasTermicas")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUG", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.MotivoRestricao", "MotivoRestricao")
                        .WithMany("RestricoesUG")
                        .HasForeignKey("MotivoRestricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.UnidadeGeradora", "UnidadeGeradora")
                        .WithMany("Restricoes")
                        .HasForeignKey("UnidadeGeradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoRestricao");

                    b.Navigation("UnidadeGeradora");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUS", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.MotivoRestricao", "MotivoRestricao")
                        .WithMany("RestricoesUS")
                        .HasForeignKey("MotivoRestricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("Restricoes")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoRestricao");

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("UnidadesGeradoras")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usinas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.TipoUsina", "TipoUsina")
                        .WithMany("Usinas")
                        .HasForeignKey("TipoUsinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoUsina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UsinaConversora", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("Conversoras")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.EquipePDP", "EquipePDP")
                        .WithMany("Membros")
                        .HasForeignKey("EquipePDPId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipePDP");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.Navigation("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Subdiretorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Usinas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.EquipePDP", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.MotivoRestricao", b =>
                {
                    b.Navigation("RestricoesUG");

                    b.Navigation("RestricoesUS");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.SemanaPMO", b =>
                {
                    b.Navigation("ArquivosDadger");

                    b.Navigation("DCAs");

                    b.Navigation("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.TipoUsina", b =>
                {
                    b.Navigation("Usinas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.Navigation("Paradas");

                    b.Navigation("Restricoes");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.Navigation("Conversoras");

                    b.Navigation("GeracoesForaMerito");

                    b.Navigation("InflexibilidadesContratadas");

                    b.Navigation("RampasTermicas");

                    b.Navigation("Restricoes");

                    b.Navigation("UnidadesGeradoras");
                });
#pragma warning restore 612, 618
        }
    }
}
