'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace DadosSAGICServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC", ConfigurationName:="DadosSAGICServiceReference.DadosSAGICSoap")>  _
    Public Interface DadosSAGICSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/IdAgentes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IdAgentes() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/IdGrupos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IdGrupos() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/DadosHorariosAgentes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DadosHorariosAgentes(ByVal IdAgente As Integer, ByVal DtIni As Date, ByVal DtFim As Date) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/DadosHorariosGrupos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DadosHorariosGrupos(ByVal Idgrupo As String, ByVal DtIni As Date, ByVal DtFim As Date) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/DadosEstadoUsina", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DadosEstadoUsina(ByVal dataBase As Date, ByVal usinas() As String, ByVal horasBase As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC/DadosCadastroRespostaDema"& _ 
            "nda", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DadosCadastroRespostaDemanda(ByVal usinas() As String) As DadosSAGICServiceReference.RespostaDemanda()
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/WS_DadosVerificados_SAGIC/DadosSAGIC")>  _
    Partial Public Class RespostaDemanda
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private usinaPDPField As String
        
        Private idAgenteField As String
        
        Private nomeAgenteField As String
        
        Private idEmpreendimentoField As String
        
        Private idNivelTensaoField As String
        
        Private idPtomedicaoField As String
        
        Private nomePtomedicaoField As String
        
        Private dataInicioVigenciaField As String
        
        Private dataFimVigenciaField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UsinaPDP() As String
            Get
                Return Me.usinaPDPField
            End Get
            Set
                Me.usinaPDPField = value
                Me.RaisePropertyChanged("UsinaPDP")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IdAgente() As String
            Get
                Return Me.idAgenteField
            End Get
            Set
                Me.idAgenteField = value
                Me.RaisePropertyChanged("IdAgente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NomeAgente() As String
            Get
                Return Me.nomeAgenteField
            End Get
            Set
                Me.nomeAgenteField = value
                Me.RaisePropertyChanged("NomeAgente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property IdEmpreendimento() As String
            Get
                Return Me.idEmpreendimentoField
            End Get
            Set
                Me.idEmpreendimentoField = value
                Me.RaisePropertyChanged("IdEmpreendimento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property IdNivelTensao() As String
            Get
                Return Me.idNivelTensaoField
            End Get
            Set
                Me.idNivelTensaoField = value
                Me.RaisePropertyChanged("IdNivelTensao")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property IdPtomedicao() As String
            Get
                Return Me.idPtomedicaoField
            End Get
            Set
                Me.idPtomedicaoField = value
                Me.RaisePropertyChanged("IdPtomedicao")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property NomePtomedicao() As String
            Get
                Return Me.nomePtomedicaoField
            End Get
            Set
                Me.nomePtomedicaoField = value
                Me.RaisePropertyChanged("NomePtomedicao")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property DataInicioVigencia() As String
            Get
                Return Me.dataInicioVigenciaField
            End Get
            Set
                Me.dataInicioVigenciaField = value
                Me.RaisePropertyChanged("DataInicioVigencia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property DataFimVigencia() As String
            Get
                Return Me.dataFimVigenciaField
            End Get
            Set
                Me.dataFimVigenciaField = value
                Me.RaisePropertyChanged("DataFimVigencia")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DadosSAGICSoapChannel
        Inherits DadosSAGICServiceReference.DadosSAGICSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DadosSAGICSoapClient
        Inherits System.ServiceModel.ClientBase(Of DadosSAGICServiceReference.DadosSAGICSoap)
        Implements DadosSAGICServiceReference.DadosSAGICSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IdAgentes() As System.Data.DataSet Implements DadosSAGICServiceReference.DadosSAGICSoap.IdAgentes
            Return MyBase.Channel.IdAgentes
        End Function
        
        Public Function IdGrupos() As System.Data.DataSet Implements DadosSAGICServiceReference.DadosSAGICSoap.IdGrupos
            Return MyBase.Channel.IdGrupos
        End Function
        
        Public Function DadosHorariosAgentes(ByVal IdAgente As Integer, ByVal DtIni As Date, ByVal DtFim As Date) As System.Data.DataSet Implements DadosSAGICServiceReference.DadosSAGICSoap.DadosHorariosAgentes
            Return MyBase.Channel.DadosHorariosAgentes(IdAgente, DtIni, DtFim)
        End Function
        
        Public Function DadosHorariosGrupos(ByVal Idgrupo As String, ByVal DtIni As Date, ByVal DtFim As Date) As System.Data.DataSet Implements DadosSAGICServiceReference.DadosSAGICSoap.DadosHorariosGrupos
            Return MyBase.Channel.DadosHorariosGrupos(Idgrupo, DtIni, DtFim)
        End Function
        
        Public Function DadosEstadoUsina(ByVal dataBase As Date, ByVal usinas() As String, ByVal horasBase As Integer) As System.Data.DataSet Implements DadosSAGICServiceReference.DadosSAGICSoap.DadosEstadoUsina
            Return MyBase.Channel.DadosEstadoUsina(dataBase, usinas, horasBase)
        End Function
        
        Public Function DadosCadastroRespostaDemanda(ByVal usinas() As String) As DadosSAGICServiceReference.RespostaDemanda() Implements DadosSAGICServiceReference.DadosSAGICSoap.DadosCadastroRespostaDemanda
            Return MyBase.Channel.DadosCadastroRespostaDemanda(usinas)
        End Function
    End Class
End Namespace
