// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDPW.Infrastructure.Data;

#nullable disable

namespace PDPW.Infrastructure.Migrations
{
    [DbContext(typeof(PdpwDbContext))]
    [Migration("20251226144838_SeedUnicoConsolidado")]
    partial class SeedUnicoConsolidado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PDPW.Domain.Entities.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoCompleto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiretorioId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiretorioId");

                    b.ToTable("Arquivos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processado")
                        .HasColumnType("bit");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("ArquivosDadger");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadgerValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArquivoDadgerId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Linha")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoDadgerId");

                    b.HasIndex("Chave");

                    b.ToTable("ArquivosDadgerValores");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Balanco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("Carga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deficit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Geracao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Intercambio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Perdas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubsistemaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaId");

                    b.ToTable("Balancos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Carga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CargaMWmed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CargaVerificada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrevisaoCarga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubsistemaId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaId");

                    b.ToTable("Cargas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("DadosConsolidados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAprovacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("DCAs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aprovado")
                        .HasColumnType("bit");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("DCAId")
                        .HasColumnType("int");

                    b.Property<string>("DadosRevisados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRevisao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SemanaPMOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DCAId");

                    b.HasIndex("SemanaPMOId");

                    b.ToTable("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DadoEnergetico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeDisponivel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoUsina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProducaoMWh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia");

                    b.ToTable("DadosEnergeticos");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiretorioPaiId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DiretorioPaiId");

                    b.ToTable("Diretorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique()
                        .HasFilter("[CNPJ] IS NOT NULL");

                    b.HasIndex("Nome");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CNPJ = "00341583000171",
                            DataCriacao = new DateTime(1984, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@itaipu.gov.br",
                            Endereco = "Av. Tancredo Neves, 6731 - Foz do Iguaçu, PR",
                            Nome = "Itaipu Binacional",
                            Telefone = "(45) 3520-5252"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CNPJ = "00357038000116",
                            DataCriacao = new DateTime(1973, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@eletronorte.gov.br",
                            Endereco = "SCN - Quadra 6 - Conjunto A - Bloco C - Brasília, DF",
                            Nome = "Eletronorte - Centrais Elétricas do Norte do Brasil",
                            Telefone = "(61) 3429-5151"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CNPJ = "23047150000113",
                            DataCriacao = new DateTime(1957, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ouvidoria@furnas.com.br",
                            Endereco = "Rua Real Grandeza, 219 - Rio de Janeiro, RJ",
                            Nome = "Furnas Centrais Elétricas",
                            Telefone = "(21) 2528-5600"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CNPJ = "33541368000116",
                            DataCriacao = new DateTime(1945, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "faleconosco@chesf.gov.br",
                            Endereco = "Rua Delmiro Gouveia, 333 - Recife, PE",
                            Nome = "Chesf - Companhia Hidro Elétrica do São Francisco",
                            Telefone = "(81) 3229-2300"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CNPJ = "00073957000146",
                            DataCriacao = new DateTime(1968, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "comunicacao@eletrosul.gov.br",
                            Endereco = "Av. Prefeito Osmar Cunha, 183 - Florianópolis, SC",
                            Nome = "Eletrosul Centrais Elétricas",
                            Telefone = "(48) 3231-7000"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CNPJ = "60933603000178",
                            DataCriacao = new DateTime(1966, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ouvidoria@cesp.com.br",
                            Endereco = "Av. Nossa Senhora do Sabará, 5312 - São Paulo, SP",
                            Nome = "CESP - Companhia Energética de São Paulo",
                            Telefone = "(11) 3138-7000"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CNPJ = "42540211000167",
                            DataCriacao = new DateTime(1997, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eletronuclear@eletronuclear.gov.br",
                            Endereco = "Rua da Candelária, 65 - Rio de Janeiro, RJ",
                            Nome = "Eletronuclear - Eletrobrás Termonuclear",
                            Telefone = "(21) 2588-1000"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CNPJ = "76483817000120",
                            DataCriacao = new DateTime(1954, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "copel@copel.com",
                            Endereco = "Rua José Izidoro Biazetto, 158 - Curitiba, PR",
                            Nome = "COPEL - Companhia Paranaense de Energia",
                            Telefone = "(41) 3331-4011"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CNPJ = "17155730000164",
                            DataCriacao = new DateTime(1952, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@cemig.com.br",
                            Endereco = "Av. Barbacena, 1200 - Belo Horizonte, MG",
                            Nome = "CEMIG - Companhia Energética de Minas Gerais",
                            Telefone = "(31) 3506-5000"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CNPJ = "02429144000193",
                            DataCriacao = new DateTime(1998, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "contato@cpfl.com.br",
                            Endereco = "Rod. Eng. Miguel Noel Nascentes Burnier - Campinas, SP",
                            Nome = "CPFL Energia",
                            Telefone = "(19) 3756-8000"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.EquipePDP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Coordenador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EquipesPDP");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Coordenador = "João Silva Santos",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Responsável pela programação diária de produção da região Nordeste",
                            Email = "operacao.ne@ons.org.br",
                            Nome = "Equipe de Operação Nordeste",
                            Telefone = "(81) 3421-5000"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Coordenador = "Maria Oliveira Costa",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Responsável pela programação diária de produção da região Sudeste/Centro-Oeste",
                            Email = "operacao.se@ons.org.br",
                            Nome = "Equipe de Operação Sudeste",
                            Telefone = "(21) 3444-5500"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Coordenador = "Carlos Eduardo Ferreira",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Responsável pela programação diária de produção da região Sul",
                            Email = "operacao.sul@ons.org.br",
                            Nome = "Equipe de Operação Sul",
                            Telefone = "(41) 3333-4400"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Coordenador = "Ana Paula Rodrigues",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Responsável pela programação diária de produção da região Norte",
                            Email = "operacao.norte@ons.org.br",
                            Nome = "Equipe de Operação Norte",
                            Telefone = "(92) 3232-1100"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Coordenador = "Roberto Mendes Lima",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Responsável pelo planejamento de médio e longo prazo da operação",
                            Email = "planejamento@ons.org.br",
                            Nome = "Equipe de Planejamento Energético",
                            Telefone = "(21) 3444-5600"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.GerForaMerito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GeracaoMWmed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("GeracoesForaMerito");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.InflexibilidadeContratada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Contrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GeracaoMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("InflexibilidadesContratadas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Intercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnergiaIntercambiada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubsistemaDestino")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SubsistemaOrigem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("DataReferencia", "SubsistemaOrigem", "SubsistemaDestino");

                    b.ToTable("Intercambios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ModalidadeOpTermica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CustoOperacional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PotenciaMaxima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotenciaMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ModalidadesOpTermica");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.MotivoRestricao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MotivosRestricao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Categoria = "Manutenção",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Parada para manutenção preventiva ou corretiva",
                            Nome = "Manutenção Programada"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Categoria = "Técnica",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Problema em equipamento que restringe a geração",
                            Nome = "Falha de Equipamento"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Categoria = "Hidráulica",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Vazão insuficiente para geração plena",
                            Nome = "Restrição Hidráulica"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Categoria = "Elétrica",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Limitação no sistema de transmissão",
                            Nome = "Restrição de Transmissão"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Categoria = "Operacional",
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Teste de equipamentos ou sistemas",
                            Nome = "Teste Operacional"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Observacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioAutor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Observacoes");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ParadaUG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoParada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Programada")
                        .HasColumnType("bit");

                    b.Property<int>("UnidadeGeradoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeGeradoraId");

                    b.ToTable("ParadasUG");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RampasUsinaTermica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RampaDescida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RampaSubida")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TempoParada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TempoPartida")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("RampasUsinasTermicas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Parametros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoRelatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsuarioGeracao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUG", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotivoRestricaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PotenciaRestrita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadeGeradoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoRestricaoId");

                    b.HasIndex("UnidadeGeradoraId");

                    b.ToTable("RestricoesUG");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeRestrita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MotivoRestricaoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MotivoRestricaoId");

                    b.HasIndex("UsinaId");

                    b.ToTable("RestricoesUS");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.SemanaPMO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "Ano")
                        .IsUnique();

                    b.ToTable("SemanasPMO");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 49
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2024,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 50
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2024,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 51,
                            Observacoes = "SEMANA ATUAL - Natal 2024"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2024,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 52
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 1
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 2
                        },
                        new
                        {
                            Id = 7,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 3
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 4
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 5
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 6
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 7
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 8
                        },
                        new
                        {
                            Id = 13,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 9
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 10
                        },
                        new
                        {
                            Id = 15,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 11
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2025,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataFim = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = 12
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.TipoUsina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FonteEnergia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("TiposUsina");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da força da água",
                            FonteEnergia = "Hídrica",
                            Nome = "Hidrelétrica"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da queima de combustíveis",
                            FonteEnergia = "Combustíveis Fósseis / Biomassa",
                            Nome = "Térmica"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da força dos ventos",
                            FonteEnergia = "Eólica",
                            Nome = "Eólica"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da luz solar",
                            FonteEnergia = "Solar",
                            Nome = "Solar"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da fissão nuclear",
                            FonteEnergia = "Nuclear",
                            Nome = "Nuclear"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pequena Central Hidrelétrica",
                            FonteEnergia = "Hídrica",
                            Nome = "PCH"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Central Geradora Hidrelétrica",
                            FonteEnergia = "Hídrica",
                            Nome = "CGH"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Usina que gera energia através da queima de biomassa",
                            FonteEnergia = "Biomassa",
                            Nome = "Biomassa"
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataComissionamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PotenciaMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PotenciaNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("UsinaId");

                    b.ToTable("UnidadesGeradoras");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeInstalada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoUsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("Nome");

                    b.HasIndex("TipoUsinaId");

                    b.ToTable("Usinas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CapacidadeInstalada = 14000.00m,
                            Codigo = "UHE-ITAIPU",
                            DataCriacao = new DateTime(1984, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1984, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 1,
                            Localizacao = "Foz do Iguaçu, PR",
                            Nome = "Usina Hidrelétrica de Itaipu",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CapacidadeInstalada = 11233.00m,
                            Codigo = "UHE-BELO-MONTE",
                            DataCriacao = new DateTime(2016, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2016, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Altamira, PA",
                            Nome = "Usina Hidrelétrica Belo Monte",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CapacidadeInstalada = 8370.00m,
                            Codigo = "UHE-TUCURUI",
                            DataCriacao = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Tucuruí, PA",
                            Nome = "Usina Hidrelétrica de Tucuruí",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CapacidadeInstalada = 3568.00m,
                            Codigo = "UHE-SANTO-ANTONIO",
                            DataCriacao = new DateTime(2012, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2012, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Porto Velho, RO",
                            Nome = "Usina Hidrelétrica Santo Antônio",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CapacidadeInstalada = 3750.00m,
                            Codigo = "UHE-JIRAU",
                            DataCriacao = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 2,
                            Localizacao = "Porto Velho, RO",
                            Nome = "Usina Hidrelétrica Jirau",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CapacidadeInstalada = 3444.00m,
                            Codigo = "UHE-ILHA-SOLTEIRA",
                            DataCriacao = new DateTime(1973, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1973, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 3,
                            Localizacao = "Ilha Solteira, SP",
                            Nome = "Usina Hidrelétrica Ilha Solteira",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CapacidadeInstalada = 3162.00m,
                            Codigo = "UHE-XINGO",
                            DataCriacao = new DateTime(1994, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1994, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 4,
                            Localizacao = "Canindé de São Francisco, SE",
                            Nome = "Usina Hidrelétrica Xingó",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CapacidadeInstalada = 2462.00m,
                            Codigo = "UHE-PAULO-AFONSO-IV",
                            DataCriacao = new DateTime(1979, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1979, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 4,
                            Localizacao = "Paulo Afonso, BA",
                            Nome = "Usina Hidrelétrica Paulo Afonso IV",
                            TipoUsinaId = 1
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CapacidadeInstalada = 640.00m,
                            Codigo = "UTN-ANGRA-I",
                            DataCriacao = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 7,
                            Localizacao = "Angra dos Reis, RJ",
                            Nome = "Usina Termonuclear Angra I",
                            TipoUsinaId = 5
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CapacidadeInstalada = 1350.00m,
                            Codigo = "UTN-ANGRA-II",
                            DataCriacao = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataOperacao = new DateTime(2001, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpresaId = 7,
                            Localizacao = "Angra dos Reis, RJ",
                            Nome = "Usina Termonuclear Angra II",
                            TipoUsinaId = 5
                        });
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UsinaConversora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CapacidadeConversao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Eficiencia")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoConversao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsinaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsinaId");

                    b.ToTable("UsinasConversoras");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("EquipePDPId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Perfil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EquipePDPId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Arquivo", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Diretorio", "Diretorio")
                        .WithMany("Arquivos")
                        .HasForeignKey("DiretorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretorio");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("ArquivosDadger")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadgerValor", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.ArquivoDadger", "ArquivoDadger")
                        .WithMany("Valores")
                        .HasForeignKey("ArquivoDadgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArquivoDadger");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("DCAs")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCR", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.DCA", "DCA")
                        .WithMany("DCRs")
                        .HasForeignKey("DCAId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PDPW.Domain.Entities.SemanaPMO", "SemanaPMO")
                        .WithMany("DCRs")
                        .HasForeignKey("SemanaPMOId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DCA");

                    b.Navigation("SemanaPMO");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Diretorio", "DiretorioPai")
                        .WithMany("Subdiretorios")
                        .HasForeignKey("DiretorioPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DiretorioPai");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.GerForaMerito", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("GeracoesForaMerito")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.InflexibilidadeContratada", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("InflexibilidadesContratadas")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ParadaUG", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.UnidadeGeradora", "UnidadeGeradora")
                        .WithMany("Paradas")
                        .HasForeignKey("UnidadeGeradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadeGeradora");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RampasUsinaTermica", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("RampasTermicas")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUG", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.MotivoRestricao", "MotivoRestricao")
                        .WithMany("RestricoesUG")
                        .HasForeignKey("MotivoRestricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.UnidadeGeradora", "UnidadeGeradora")
                        .WithMany("Restricoes")
                        .HasForeignKey("UnidadeGeradoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoRestricao");

                    b.Navigation("UnidadeGeradora");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.RestricaoUS", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.MotivoRestricao", "MotivoRestricao")
                        .WithMany("RestricoesUS")
                        .HasForeignKey("MotivoRestricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("Restricoes")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoRestricao");

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("UnidadesGeradoras")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usinas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PDPW.Domain.Entities.TipoUsina", "TipoUsina")
                        .WithMany("Usinas")
                        .HasForeignKey("TipoUsinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("TipoUsina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UsinaConversora", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.Usina", "Usina")
                        .WithMany("Conversoras")
                        .HasForeignKey("UsinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usina");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PDPW.Domain.Entities.EquipePDP", "EquipePDP")
                        .WithMany("Membros")
                        .HasForeignKey("EquipePDPId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipePDP");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.ArquivoDadger", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.DCA", b =>
                {
                    b.Navigation("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Diretorio", b =>
                {
                    b.Navigation("Arquivos");

                    b.Navigation("Subdiretorios");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Usinas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.EquipePDP", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.MotivoRestricao", b =>
                {
                    b.Navigation("RestricoesUG");

                    b.Navigation("RestricoesUS");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.SemanaPMO", b =>
                {
                    b.Navigation("ArquivosDadger");

                    b.Navigation("DCAs");

                    b.Navigation("DCRs");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.TipoUsina", b =>
                {
                    b.Navigation("Usinas");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.UnidadeGeradora", b =>
                {
                    b.Navigation("Paradas");

                    b.Navigation("Restricoes");
                });

            modelBuilder.Entity("PDPW.Domain.Entities.Usina", b =>
                {
                    b.Navigation("Conversoras");

                    b.Navigation("GeracoesForaMerito");

                    b.Navigation("InflexibilidadesContratadas");

                    b.Navigation("RampasTermicas");

                    b.Navigation("Restricoes");

                    b.Navigation("UnidadesGeradoras");
                });
#pragma warning restore 612, 618
        }
    }
}
